server:
  port: 8762

spring:
  application:
    name: service-registry

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8762/eureka
    register-with-eureka: false
    fetch-registry: false
