spring:
  application:
    name: api-gateway
  output:
    ansi:
      enabled: always
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/users/**
          filters:
            - RewritePath=/users/(?<path>.*), /$\{path}
        - id: project-service
          uri: lb://project-service
          predicates:
            - Path=/projects/**
          filters:
            - RewritePath=/projects/(?<path>.*), /$\{path}
        - id: openapi
          uri: http://localhost:${server.port}
          predicates:
            - Path=/v3/api-docs/**
          filters:
            - RewritePath=/v3/api-docs/(?<path>.*), /$\{path}/v3/api-docs

  main:
    web-application-type: reactive

springdoc:
  api-docs:
    version: OPENAPI_3_0
    enabled: true
  swagger-ui:
    enabled: true
    path: /swagger
    config-url: /v3/api-docs/swagger-config
    urls:
      - name: users
        url: /users/v3/api-docs
      - name: projects
        url: /projects/v3/api-docs
      - name: Gateway
        url: /v3/api-docs


eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: ${EUREKA_SERVER_ADDRESS:http://localhost:8762/eureka}
  instance:
    prefer-ip-address: true


