spring:
  application:
    name: user-service

server:
  port: 8092

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: ${EUREKA_URI:http://localhost:8762/eureka}
