spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: passwordpw
    url: jdbc:postgresql://localhost:5432/
  jpa:
    hibernate:
      ddl-auto: update
    generate-ddl: true